### ISSUE TITLE
pretrained model for resnet50 backbone

### ISSUE THREAD

**Issue by zhangyuygss** [feipan664/IntraDA#3]
Hey, I want to try your model with resnet50 as the backbone, where should I download the pretrained model? Thanks!

**Comment by feipanir** [comment]
Hi we currently haven't tested on ResNet50 as the backbone, rather we choose ResNet101 because it could generate pretty accurate segmentation maps during inter-DA step. If you really wanna try on ResNet50, though we could not guarantee final performance, we recommend you to look at https://pytorch.org/docs/stable/_modules/torchvision/models/segmentation/segmentation.html#fcn_resnet50

**Comment by zhangyuygss** [comment]
Thanks, I'm trying resnet50 to save training time. I assume the performance might drop a little, but the UDA framework will still work, am I right?

**Comment by feipanir** [comment]
Yes ideally it would still work.
